<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aufgabe2\Aufgabe2.csproj" />
    <ProjectReference Include="..\FahrzeugVerwaltung.Data.DB\FahrzeugVerwaltung.Data.DB.csproj" />
  </ItemGroup>

</Project>
